export const v4model = {
  'dtmi:com:example:base;1': {
    SupplementalTypes: [],
    SupplementalProperties: {},
    UndefinedTypes: [],
    UndefinedProperties: {},
    comment: null,
    description: {},
    displayName: {},
    languageMajorVersion: 4,
    Id: 'dtmi:com:example:base;1',
    ChildOf: 'dtmi:com:example;1',
    DefinedIn: 'dtmi:com:example;1',
    EntityKind: 'Interface',
    ClassId: 'dtmi:dtdl:class:Interface;4',
    contents: {},
    commands: {},
    components: {},
    properties: {},
    relationships: {},
    telemetries: {},
    extendedBy: ['dtmi:com:example;1'],
    extends: [],
    schemas: [],
  },
  'dtmi:com:example:_contents:__byteType;1': {
    SupplementalTypes: [],
    SupplementalProperties: {},
    UndefinedTypes: [],
    UndefinedProperties: {},
    comment: null,
    description: {
      en: 'Property Defining an examples byte',
    },
    displayName: {},
    languageMajorVersion: 4,
    Id: 'dtmi:com:example:_contents:__byteType;1',
    ChildOf: 'dtmi:com:example;1',
    DefinedIn: 'dtmi:com:example;1',
    EntityKind: 'Property',
    name: 'byteType',
    ClassId: 'dtmi:dtdl:class:Property;4',
    schema: 'dtmi:dtdl:instance:Schema:byte;4',
    writable: false,
  },
  'dtmi:com:example:_contents:__bytesType;1': {
    SupplementalTypes: [],
    SupplementalProperties: {},
    UndefinedTypes: [],
    UndefinedProperties: {},
    comment: null,
    description: {
      en: 'Property Defining an examples bytes',
    },
    displayName: {},
    languageMajorVersion: 4,
    Id: 'dtmi:com:example:_contents:__bytesType;1',
    ChildOf: 'dtmi:com:example;1',
    DefinedIn: 'dtmi:com:example;1',
    EntityKind: 'Property',
    name: 'bytesType',
    ClassId: 'dtmi:dtdl:class:Property;4',
    schema: 'dtmi:dtdl:instance:Schema:bytes;4',
    writable: false,
  },
  'dtmi:com:example:_contents:__decimalType;1': {
    SupplementalTypes: [],
    SupplementalProperties: {},
    UndefinedTypes: [],
    UndefinedProperties: {},
    comment: null,
    description: {
      en: 'Property Defining an examples decimal',
    },
    displayName: {},
    languageMajorVersion: 4,
    Id: 'dtmi:com:example:_contents:__decimalType;1',
    ChildOf: 'dtmi:com:example;1',
    DefinedIn: 'dtmi:com:example;1',
    EntityKind: 'Property',
    name: 'decimalType',
    ClassId: 'dtmi:dtdl:class:Property;4',
    schema: 'dtmi:dtdl:instance:Schema:decimal;4',
    writable: false,
  },
  'dtmi:com:example:_contents:__shortType;1': {
    SupplementalTypes: [],
    SupplementalProperties: {},
    UndefinedTypes: [],
    UndefinedProperties: {},
    comment: null,
    description: {
      en: 'Property Defining an examples short',
    },
    displayName: {},
    languageMajorVersion: 4,
    Id: 'dtmi:com:example:_contents:__shortType;1',
    ChildOf: 'dtmi:com:example;1',
    DefinedIn: 'dtmi:com:example;1',
    EntityKind: 'Property',
    name: 'shortType',
    ClassId: 'dtmi:dtdl:class:Property;4',
    schema: 'dtmi:dtdl:instance:Schema:short;4',
    writable: false,
  },
  'dtmi:com:example:_contents:__unsignedByteType;1': {
    SupplementalTypes: [],
    SupplementalProperties: {},
    UndefinedTypes: [],
    UndefinedProperties: {},
    comment: null,
    description: {
      en: 'Property Defining an examples unsignedByte',
    },
    displayName: {},
    languageMajorVersion: 4,
    Id: 'dtmi:com:example:_contents:__unsignedByteType;1',
    ChildOf: 'dtmi:com:example;1',
    DefinedIn: 'dtmi:com:example;1',
    EntityKind: 'Property',
    name: 'unsignedByteType',
    ClassId: 'dtmi:dtdl:class:Property;4',
    schema: 'dtmi:dtdl:instance:Schema:unsignedByte;4',
    writable: false,
  },
  'dtmi:com:example:_contents:__unsignedIntegerType;1': {
    SupplementalTypes: [],
    SupplementalProperties: {},
    UndefinedTypes: [],
    UndefinedProperties: {},
    comment: null,
    description: {
      en: 'Property Defining an examples unsignedInteger',
    },
    displayName: {},
    languageMajorVersion: 4,
    Id: 'dtmi:com:example:_contents:__unsignedIntegerType;1',
    ChildOf: 'dtmi:com:example;1',
    DefinedIn: 'dtmi:com:example;1',
    EntityKind: 'Property',
    name: 'unsignedIntegerType',
    ClassId: 'dtmi:dtdl:class:Property;4',
    schema: 'dtmi:dtdl:instance:Schema:unsignedInteger;4',
    writable: false,
  },
  'dtmi:com:example:_contents:__unsignedLongType;1': {
    SupplementalTypes: [],
    SupplementalProperties: {},
    UndefinedTypes: [],
    UndefinedProperties: {},
    comment: null,
    description: {
      en: 'Property Defining an examples unsignedLong',
    },
    displayName: {},
    languageMajorVersion: 4,
    Id: 'dtmi:com:example:_contents:__unsignedLongType;1',
    ChildOf: 'dtmi:com:example;1',
    DefinedIn: 'dtmi:com:example;1',
    EntityKind: 'Property',
    name: 'unsignedLongType',
    ClassId: 'dtmi:dtdl:class:Property;4',
    schema: 'dtmi:dtdl:instance:Schema:unsignedLong;4',
    writable: false,
  },
  'dtmi:com:example:_contents:__unsignedShortType;1': {
    SupplementalTypes: [],
    SupplementalProperties: {},
    UndefinedTypes: [],
    UndefinedProperties: {},
    comment: null,
    description: {
      en: 'Property Defining an examples unsignedShort',
    },
    displayName: {},
    languageMajorVersion: 4,
    Id: 'dtmi:com:example:_contents:__unsignedShortType;1',
    ChildOf: 'dtmi:com:example;1',
    DefinedIn: 'dtmi:com:example;1',
    EntityKind: 'Property',
    name: 'unsignedShortType',
    ClassId: 'dtmi:dtdl:class:Property;4',
    schema: 'dtmi:dtdl:instance:Schema:unsignedShort;4',
    writable: false,
  },
  'dtmi:com:example:_contents:__uuidType;1': {
    SupplementalTypes: [],
    SupplementalProperties: {},
    UndefinedTypes: [],
    UndefinedProperties: {},
    comment: null,
    description: {
      en: 'Property Defining an examples uuid',
    },
    displayName: {},
    languageMajorVersion: 4,
    Id: 'dtmi:com:example:_contents:__uuidType;1',
    ChildOf: 'dtmi:com:example;1',
    DefinedIn: 'dtmi:com:example;1',
    EntityKind: 'Property',
    name: 'uuidType',
    ClassId: 'dtmi:dtdl:class:Property;4',
    schema: 'dtmi:dtdl:instance:Schema:uuid;4',
    writable: false,
  },
  'dtmi:com:example:_contents:__scaledDecimalType;1': {
    SupplementalTypes: [],
    SupplementalProperties: {},
    UndefinedTypes: [],
    UndefinedProperties: {},
    comment: null,
    description: {
      en: 'Property Defining an examples scaledDecimal',
    },
    displayName: {},
    languageMajorVersion: 4,
    Id: 'dtmi:com:example:_contents:__scaledDecimalType;1',
    ChildOf: 'dtmi:com:example;1',
    DefinedIn: 'dtmi:com:example;1',
    EntityKind: 'Property',
    name: 'scaledDecimalType',
    ClassId: 'dtmi:dtdl:class:Property;4',
    schema: 'dtmi:standard:schema:scaledDecimal;4',
    writable: false,
  },
  'dtmi:com:example:InterfaceSchema:_fields:__selfReferentialSchema;1': {
    SupplementalTypes: [],
    SupplementalProperties: {},
    UndefinedTypes: [],
    UndefinedProperties: {},
    comment: null,
    description: {},
    displayName: {},
    languageMajorVersion: 4,
    Id: 'dtmi:com:example:InterfaceSchema:_fields:__selfReferentialSchema;1',
    ChildOf: 'dtmi:com:example:InterfaceSchema;1',
    DefinedIn: 'dtmi:com:example;1',
    EntityKind: 'Field',
    name: 'selfReferentialSchema',
    schema: 'dtmi:com:example:InterfaceSchema;1',
    ClassId: 'dtmi:dtdl:class:Field;4',
  },
  'dtmi:com:example:InterfaceSchema;1': {
    SupplementalTypes: [],
    SupplementalProperties: {},
    UndefinedTypes: [],
    UndefinedProperties: {},
    comment: null,
    description: {},
    displayName: {},
    languageMajorVersion: 4,
    Id: 'dtmi:com:example:InterfaceSchema;1',
    ChildOf: 'dtmi:com:example;1',
    DefinedIn: 'dtmi:com:example;1',
    EntityKind: 'Object',
    ClassId: 'dtmi:dtdl:class:Object;4',
    fields: ['dtmi:com:example:InterfaceSchema:_fields:__selfReferentialSchema;1'],
  },
  'dtmi:com:example;1': {
    SupplementalTypes: [],
    SupplementalProperties: {},
    UndefinedTypes: [],
    UndefinedProperties: {},
    comment: null,
    description: {},
    displayName: {},
    languageMajorVersion: 4,
    Id: 'dtmi:com:example;1',
    ChildOf: null,
    DefinedIn: null,
    EntityKind: 'Interface',
    ClassId: 'dtmi:dtdl:class:Interface;4',
    contents: {
      byteType: 'dtmi:com:example:_contents:__byteType;1',
      bytesType: 'dtmi:com:example:_contents:__bytesType;1',
      decimalType: 'dtmi:com:example:_contents:__decimalType;1',
      shortType: 'dtmi:com:example:_contents:__shortType;1',
      unsignedByteType: 'dtmi:com:example:_contents:__unsignedByteType;1',
      unsignedIntegerType: 'dtmi:com:example:_contents:__unsignedIntegerType;1',
      unsignedLongType: 'dtmi:com:example:_contents:__unsignedLongType;1',
      unsignedShortType: 'dtmi:com:example:_contents:__unsignedShortType;1',
      uuidType: 'dtmi:com:example:_contents:__uuidType;1',
      scaledDecimalType: 'dtmi:com:example:_contents:__scaledDecimalType;1',
    },
    commands: {},
    components: {},
    properties: {
      byteType: 'dtmi:com:example:_contents:__byteType;1',
      bytesType: 'dtmi:com:example:_contents:__bytesType;1',
      decimalType: 'dtmi:com:example:_contents:__decimalType;1',
      shortType: 'dtmi:com:example:_contents:__shortType;1',
      unsignedByteType: 'dtmi:com:example:_contents:__unsignedByteType;1',
      unsignedIntegerType: 'dtmi:com:example:_contents:__unsignedIntegerType;1',
      unsignedLongType: 'dtmi:com:example:_contents:__unsignedLongType;1',
      unsignedShortType: 'dtmi:com:example:_contents:__unsignedShortType;1',
      uuidType: 'dtmi:com:example:_contents:__uuidType;1',
      scaledDecimalType: 'dtmi:com:example:_contents:__scaledDecimalType;1',
    },
    relationships: {},
    telemetries: {},
    extendedBy: [],
    extends: ['dtmi:com:example:base;1'],
    schemas: ['dtmi:com:example:InterfaceSchema;1'],
  },
  'dtmi:dtdl:instance:Schema:byte;4': {
    SupplementalTypes: [],
    SupplementalProperties: {},
    UndefinedTypes: [],
    UndefinedProperties: {},
    comment: null,
    description: {
      'en-US': 'a signed integral numeric value that is expressible in 1 byte',
    },
    displayName: {
      en: 'byte',
    },
    languageMajorVersion: 4,
    Id: 'dtmi:dtdl:instance:Schema:byte;4',
    ChildOf: null,
    DefinedIn: null,
    EntityKind: 'Byte',
    ClassId: 'dtmi:dtdl:class:Byte;4',
  },
  'dtmi:dtdl:instance:Schema:bytes;4': {
    SupplementalTypes: [],
    SupplementalProperties: {},
    UndefinedTypes: [],
    UndefinedProperties: {},
    comment: null,
    description: {
      'en-US': 'an array of bytes',
    },
    displayName: {
      en: 'bytes',
    },
    languageMajorVersion: 4,
    Id: 'dtmi:dtdl:instance:Schema:bytes;4',
    ChildOf: null,
    DefinedIn: null,
    EntityKind: 'Bytes',
    ClassId: 'dtmi:dtdl:class:Bytes;4',
  },
  'dtmi:dtdl:instance:Schema:decimal;4': {
    SupplementalTypes: [],
    SupplementalProperties: {},
    UndefinedTypes: [],
    UndefinedProperties: {},
    comment: null,
    description: {
      'en-US':
        'a string of decimal digits with an optional decimal point and fractional component, optionally preceded by a sign',
    },
    displayName: {
      en: 'decimal',
    },
    languageMajorVersion: 4,
    Id: 'dtmi:dtdl:instance:Schema:decimal;4',
    ChildOf: null,
    DefinedIn: null,
    EntityKind: 'Decimal',
    ClassId: 'dtmi:dtdl:class:Decimal;4',
  },
  'dtmi:dtdl:instance:Schema:short;4': {
    SupplementalTypes: [],
    SupplementalProperties: {},
    UndefinedTypes: [],
    UndefinedProperties: {},
    comment: null,
    description: {
      'en-US': 'a signed integral numeric value that is expressible in 2 bytes',
    },
    displayName: {
      en: 'short',
    },
    languageMajorVersion: 4,
    Id: 'dtmi:dtdl:instance:Schema:short;4',
    ChildOf: null,
    DefinedIn: null,
    EntityKind: 'Short',
    ClassId: 'dtmi:dtdl:class:Short;4',
  },
  'dtmi:dtdl:instance:Schema:unsignedByte;4': {
    SupplementalTypes: [],
    SupplementalProperties: {},
    UndefinedTypes: [],
    UndefinedProperties: {},
    comment: null,
    description: {
      'en-US': 'an unsigned integral numeric value that is expressible in 1 byte',
    },
    displayName: {
      en: 'unsignedByte',
    },
    languageMajorVersion: 4,
    Id: 'dtmi:dtdl:instance:Schema:unsignedByte;4',
    ChildOf: null,
    DefinedIn: null,
    EntityKind: 'UnsignedByte',
    ClassId: 'dtmi:dtdl:class:UnsignedByte;4',
  },
  'dtmi:dtdl:instance:Schema:unsignedInteger;4': {
    SupplementalTypes: [],
    SupplementalProperties: {},
    UndefinedTypes: [],
    UndefinedProperties: {},
    comment: null,
    description: {
      'en-US': 'an unsigned integral numeric value that is expressible in 4 bytes',
    },
    displayName: {
      en: 'unsignedInteger',
    },
    languageMajorVersion: 4,
    Id: 'dtmi:dtdl:instance:Schema:unsignedInteger;4',
    ChildOf: null,
    DefinedIn: null,
    EntityKind: 'UnsignedInteger',
    ClassId: 'dtmi:dtdl:class:UnsignedInteger;4',
  },
  'dtmi:dtdl:instance:Schema:unsignedLong;4': {
    SupplementalTypes: [],
    SupplementalProperties: {},
    UndefinedTypes: [],
    UndefinedProperties: {},
    comment: null,
    description: {
      'en-US': 'an unsigned integral numeric value that is expressible in 8 bytes',
    },
    displayName: {
      en: 'unsignedLong',
    },
    languageMajorVersion: 4,
    Id: 'dtmi:dtdl:instance:Schema:unsignedLong;4',
    ChildOf: null,
    DefinedIn: null,
    EntityKind: 'UnsignedLong',
    ClassId: 'dtmi:dtdl:class:UnsignedLong;4',
  },
  'dtmi:dtdl:instance:Schema:unsignedShort;4': {
    SupplementalTypes: [],
    SupplementalProperties: {},
    UndefinedTypes: [],
    UndefinedProperties: {},
    comment: null,
    description: {
      'en-US': 'an unsigned integral numeric value that is expressible in 2 bytes',
    },
    displayName: {
      en: 'unsignedShort',
    },
    languageMajorVersion: 4,
    Id: 'dtmi:dtdl:instance:Schema:unsignedShort;4',
    ChildOf: null,
    DefinedIn: null,
    EntityKind: 'UnsignedShort',
    ClassId: 'dtmi:dtdl:class:UnsignedShort;4',
  },
  'dtmi:dtdl:instance:Schema:uuid;4': {
    SupplementalTypes: [],
    SupplementalProperties: {},
    UndefinedTypes: [],
    UndefinedProperties: {},
    comment: null,
    description: {
      'en-US': 'a UUID string per RFC 9562',
    },
    displayName: {
      en: 'uuid',
    },
    languageMajorVersion: 4,
    Id: 'dtmi:dtdl:instance:Schema:uuid;4',
    ChildOf: null,
    DefinedIn: null,
    EntityKind: 'Uuid',
    ClassId: 'dtmi:dtdl:class:Uuid;4',
  },
  'dtmi:standard:schema:scaledDecimal;4': {
    SupplementalTypes: [],
    SupplementalProperties: {},
    UndefinedTypes: [],
    UndefinedProperties: {},
    comment: null,
    description: {
      'en-US': 'A scaled decimal number equal to `value` * 10^`scale`.',
    },
    displayName: {},
    languageMajorVersion: 4,
    Id: 'dtmi:standard:schema:scaledDecimal;4',
    ChildOf: null,
    DefinedIn: null,
    EntityKind: 'Object',
    ClassId: 'dtmi:dtdl:class:Object;4',
    fields: [
      'dtmi:standard:schema:scaledDecimal:_fields:__value;4',
      'dtmi:standard:schema:scaledDecimal:_fields:__scale;4',
    ],
  },
  'dtmi:standard:schema:scaledDecimal:_fields:__value;4': {
    SupplementalTypes: [],
    SupplementalProperties: {},
    UndefinedTypes: [],
    UndefinedProperties: {},
    comment: null,
    description: {
      'en-US': 'The significand of the scaled decimal value; not required to be integral or normalized.',
    },
    displayName: {},
    languageMajorVersion: 4,
    Id: 'dtmi:standard:schema:scaledDecimal:_fields:__value;4',
    ChildOf: 'dtmi:standard:schema:scaledDecimal;4',
    DefinedIn: null,
    EntityKind: 'Field',
    name: 'value',
    schema: 'dtmi:dtdl:instance:Schema:decimal;4',
    ClassId: 'dtmi:dtdl:class:Field;4',
  },
  'dtmi:standard:schema:scaledDecimal:_fields:__scale;4': {
    SupplementalTypes: [],
    SupplementalProperties: {},
    UndefinedTypes: [],
    UndefinedProperties: {},
    comment: null,
    description: {
      'en-US': 'Count of decimal places to shift `value` (positive left, negative right) to yield the scaled value.',
    },
    displayName: {},
    languageMajorVersion: 4,
    Id: 'dtmi:standard:schema:scaledDecimal:_fields:__scale;4',
    ChildOf: 'dtmi:standard:schema:scaledDecimal;4',
    DefinedIn: null,
    EntityKind: 'Field',
    name: 'scale',
    schema: 'dtmi:dtdl:instance:Schema:short;4',
    ClassId: 'dtmi:dtdl:class:Field;4',
  },
}
